### ISSUE TITLE
IllegalStateException when getting latest tracks of an user

### ISSUE THREAD

**Issue by sleepyfran** [vpaliyX/LastFmWrapper#1]
Whenever I try to get the latest tracks of an user I get this error:
```
IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 137 path $.recenttracks.track[0].streamable
```

As far as I know that's a GSON error, that was basically expecting a ```{``` but had an String object instead.

**Comment by vpaliy** [comment]
The issue has been fixed now.
